### ISSUE TITLE
error: unbalanced parenthesis

### ISSUE THREAD

**Issue by sdfsdhgjkbmnmxc** [imanhodjaev/test-proxy-flask#1]
![2015-09-10 21 36 35](https://cloud.githubusercontent.com/assets/149195/9797510/277d2246-5804-11e5-88fd-0e30917ee4b7.png)

**Comment by imanhodjaev** [comment]
@sdfsdhgjkbmnmxc made a fix https://github.com/imanhodjaev/test-proxy-flask/commit/8cffd950ea261928a47a9914c5dcb594a30d1bda with escaping special characters
