### ISSUE TITLE
Strange ™s

### ISSUE THREAD

**Issue by sdfsdhgjkbmnmxc** [imanhodjaev/test-proxy-flask#3]
<img width="284" alt="2015-09-11 21 54 36" src="https://cloud.githubusercontent.com/assets/149195/9823597/d5e4513a-58cf-11e5-93ee-0377f641ca33.png">

**Comment by imanhodjaev** [comment]
@sdfsdhgjkbmnmxc it was in the task to implement. You have to append `™` symbol after each work with length equal to 6

**Comment by sdfsdhgjkbmnmxc** [comment]
разных™ – ok
каждом™ – ok
синтез™атор – fail
работа™ю – fail
